### ISSUE TITLE
Yomitan Connection Failure

### ISSUE THREAD

**Issue by maiiiiixo** [kampffrosch94/jpdb-connect#19]
**Describe the bug**
I understand Yomitan isn't technically supported, but providing support for it seems like a natural extension of this project. Or maybe I'm just doing something wrong.

Anyhow, Yomitan 24.01.14.0 states "Anki Connection Failure..." in the settings page when trying to connect to 127.0.0.1:3030, with the an error message printed in the JPDB Connect 0.7.0 console. I have the default settings config. Would be great to have this fixed given Yomichan is likely to stop working one day in the future.

Error Message:

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/main.rs:189:69

**Comment by kampffrosch94** [comment]
I tried figuring out what is wrong for a bit this morning, but couldn't fix it easily.
It would take some earnest digging. (seems yomitan now sends some OPTION requests which triggered above problem, but fixing that leads to CORS errors for whatever reason)

Since I haven't been using this project myself for over a year now, I don't think I'll fix it. Sorry :(
I recommend you give the breader a try, it does the job for me
https://github.com/max-kamps/jpd-breader

I'll probably archieve this project soon.

**Comment by qtmaiuwu** [comment]
Ah, that's a shame :(. Thanks for taking a look anyway.
